version: "3"
services:
  app-nomount:
    build:
      context: .
    working_dir: /usr/src/app
    entrypoint: ash

  app-mount:
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - ./create-react-app:/usr/src/app
    entrypoint: ash

  app-mount-nodemodule-volume:
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - ./create-react-app:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    entrypoint: ash

  app-nfs:
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - nfsmount:/usr/src/app
    #command: /bin/sh -c "while sleep 1000; do :; done
    entrypoint: ash

# https://www.jeffgeerling.com/blog/2020/revisiting-docker-macs-performance-nfs-volumes
# https://cabra.dev/en/2020/04/30/slow-docker-on-mac-use-nfs/
volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/create-react-app"
  nodemodules:
