services:
  app-nomount:
    build:
      context: .
    working_dir: /usr/src/app
    entrypoint: bash
    profiles: ["app"]

  app-mount:
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - ./create-react-app:/usr/src/app
    entrypoint: bash
    profiles: ["app"]

  app-mount-nodemodule-volume:
    build:
      context: .
    working_dir: /usr/src/app
    volumes:
      - ./create-react-app:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    entrypoint: bash
    profiles: ["app"]

volumes:
  nodemodules:
